# This file is used as a global configuration for each linting tool. Inspired by
# https://github.com/psf/black/blob/master/docs/compatible_configs.md

[tool.black]
# The only deviation is to use longer line lengths.
line-length = 120

[tool.isort]
# Isort already has a compatible profile for black.
profile = 'black'
line_length = 120
known_third_party = ["wandb"]

[tool.pylint.format]
max-line-length = "120"

[tool.pylint.messages_control]
disable = """
R, C,
eval-used,
global-statement,
no-member,
import-error,
fixme,
attribute-defined-outside-init,
no-name-in-module,
protected-access,
unnecessary-lambda,
logging-format-interpolation,
broad-except
"""
enable = "C0303"  # Trailing whitespace